import { Link } from "wouter";
import { Navbar } from "@/components/layout/Navbar";
import { Button, FadeIn } from "@/components/ui/Premium";
import { ArrowRight, Star, BookOpen, Video, ShieldCheck, Trophy } from "lucide-react";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";

export function Landing() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Background Math Pattern */}
      <div className="absolute inset-0 bg-math-pattern opacity-[0.03] pointer-events-none" />
      
      <Navbar />

      <main className="pt-32 pb-20">
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-8 items-center min-h-[70vh]">
            <FadeIn className="max-w-2xl">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary font-medium text-sm mb-6">
                <Star className="w-4 h-4 fill-primary" /> 
                La plateforme #1 en Tunisie
              </div>
              <h1 className="text-5xl sm:text-6xl lg:text-7xl font-serif font-bold text-foreground leading-[1.1] mb-6">
                L'excellence académique à portée de clic.
              </h1>
              <p className="text-xl text-muted-foreground mb-8 leading-relaxed">
                Connectez-vous avec les meilleurs professeurs, suivez des cours interactifs en direct, et atteignez vos objectifs avec Étude+.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link href="/select-role">
                  <Button size="lg" className="w-full sm:w-auto text-lg group">
                    Commencer maintenant
                    <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
                <Link href="/browse">
                  <Button size="lg" variant="outline" className="w-full sm:w-auto text-lg bg-card/50 backdrop-blur">
                    Explorer les cours
                  </Button>
                </Link>
              </div>
              
              <div className="mt-12 flex items-center gap-6 text-sm font-medium text-muted-foreground">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="w-5 h-5 text-primary" /> Professeurs vérifiés
                </div>
                <div className="flex items-center gap-2">
                  <Video className="w-5 h-5 text-accent" /> Classes en direct
                </div>
              </div>
            </FadeIn>

            <FadeIn delay={0.2} className="relative hidden lg:block">
              {/* Abstract Hero Image generated by agent */}
              <div className="relative w-full aspect-square max-w-[600px] ml-auto">
                <div className="absolute inset-0 bg-gradient-to-tr from-primary/20 to-accent/20 rounded-[3rem] transform rotate-3 blur-2xl" />
                <img 
                  src={`${import.meta.env.BASE_URL}images/hero-abstract.png`}
                  alt="Étude+ Abstract Educational Composition"
                  className="relative z-10 w-full h-full object-cover rounded-[3rem] shadow-2xl border border-border/50"
                />
                
                {/* Floating Stats Card */}
                <motion.div 
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.8, duration: 0.5 }}
                  className="absolute -bottom-6 -left-6 bg-card p-6 rounded-2xl shadow-xl border border-border z-20"
                >
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
                      <Trophy className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                      <p className="text-3xl font-bold text-foreground">98%</p>
                      <p className="text-sm text-muted-foreground font-medium">Taux de réussite</p>
                    </div>
                  </div>
                </motion.div>
              </div>
            </FadeIn>
          </div>
        </section>

        {/* Features Section */}
        <section className="bg-secondary/50 py-24 mt-20 relative z-10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center max-w-2xl mx-auto mb-16">
              <h2 className="text-3xl sm:text-4xl font-serif font-bold mb-4">Une expérience d'apprentissage complète</h2>
              <p className="text-lg text-muted-foreground">Tout ce dont vous avez besoin pour réussir, réuni sur une seule plateforme intuitive.</p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              {[
                { icon: Video, title: "Classes Virtuelles", desc: "Vidéoconférence HD intégrée, tableau blanc interactif et chat en direct.", color: "text-accent", bg: "bg-accent/10" },
                { icon: BookOpen, title: "Ressources Riches", desc: "Accédez aux supports de cours, quiz, et devoirs organisés par chapitre.", color: "text-primary", bg: "bg-primary/10" },
                { icon: ShieldCheck, title: "Paiement Sécurisé", desc: "Payez vos cours en toute sécurité en Dinars Tunisiens (TND).", color: "text-green-500", bg: "bg-green-500/10" }
              ].map((f, i) => (
                <FadeIn key={i} delay={0.1 * i}>
                  <div className="bg-card rounded-2xl p-8 border border-border shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300">
                    <div className={cn("w-14 h-14 rounded-xl flex items-center justify-center mb-6", f.bg)}>
                      <f.icon className={cn("w-7 h-7", f.color)} />
                    </div>
                    <h3 className="text-xl font-bold mb-3">{f.title}</h3>
                    <p className="text-muted-foreground leading-relaxed">{f.desc}</p>
                  </div>
                </FadeIn>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
